@rooturl=http://localhost:9001/api/v1
# auth end point
@authEP={{rooturl}}/auth
# Book end point
@bookEP={{rooturl}}/books

@borrowEp = {{rooturl}}/borrow

POST {{authEP}}/login
Content-Type: application/json

{
  "email": "john@gmail.com",
  "password":"password"
}

###
POST {{authEP}}/register
Content-Type: application/json

{
  "fName": "john",
  "lName" : "Doe",
  "email" : "john@gmail.com",
  "phone" : "1234567",
  "password" : "password"
}

### 
GET {{authEP}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwiaWF0IjoxNzQxODE4ODc0LCJleHAiOjE3NDE5MDUyNzR9.UFYTfYS976Ghegu43Lc9HuvrGZAMMsqXWNRsRLLeH9A

### get students details
GET {{authEP}}/students
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwiaWF0IjoxNzQxODE4ODc0LCJleHAiOjE3NDE5MDUyNzR9.UFYTfYS976Ghegu43Lc9HuvrGZAMMsqXWNRsRLLeH9A

### create a book 
POST {{bookEP}}/add
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwiaWF0IjoxNzQyMDgwODAwLCJleHAiOjE3NDIxNjcyMDB9.MFI-dyOtRukcsMe3TO58X4rzaXW5mmTBgtVUq4RKHrM

{ "title": "The Future of Blockchain",
    "author": "Ms. Clara Green",
    "thumbnail": "https://wallpapercave.com/wp/g2jzVAw.jpg",
    "isbn": "54247b",
    "genre": "Blockchain",
    "publishedYear": 2023, 
    "description" : "sdfjlasdjflsadjlfjl"
  }


###
GET {{bookEP}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwiaWF0IjoxNzQyMDgwODAwLCJleHAiOjE3NDIxNjcyMDB9.MFI-dyOtRukcsMe3TO58X4rzaXW5mmTBgtVUq4RKHrM

### get the public books
GET {{bookEP}}/pub-books

### Delete the book 
DELETE {{bookEP}}/67cfdeac96be4f78cea39791
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwiaWF0IjoxNzQyMDgwODAwLCJleHAiOjE3NDIxNjcyMDB9.MFI-dyOtRukcsMe3TO58X4rzaXW5mmTBgtVUq4RKHrM


### update the book
PUT {{bookEP}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwiaWF0IjoxNzQxNjc4ODkwLCJleHAiOjE3NDE3NjUyOTB9.xcwFQ9W0OQfRKWzctRZTy9qAdGXlP06bpHPaZhzvLlc
Content-Type: application/json

{
 "status": "inactive",
    "title": "book1",
    "author": "book author",
    "isbn": "13z446",
    "publishedYear": 2020,
    "thumbnail": "https://wallpapercave.com/wp/rdYAno5.jpg",
    "description": "asljkdfhsahgfslkk",
    "isAvailable": true,
    "expectedAvailable": null,
    "_id": "67bbbdd62e9edf0d5a0770ac",
    "genre": "horror"
}

###

GET {{authEP}}/renew-jwt
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwiaWF0IjoxNzQwNDQwNjk0LCJleHAiOjE3NDE3MzY2OTR9.uEIjYc7V_8maGkLH4ghGETUCdKY1vuJf_5lUXeg_eKo

### creating the Borrow
POST {{borrowEp}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwiaWF0IjoxNzQyMDgwODAwLCJleHAiOjE3NDIxNjcyMDB9.MFI-dyOtRukcsMe3TO58X4rzaXW5mmTBgtVUq4RKHrM
Content-Type: application/json

{
  "bookId" : "67bbbdd62e9edf0d5a0770ac" ,
  "title" : "book1",
  "thumbnail" : "https://wallpapercave.com/wp/rdYAno5.jpg"
}